# -*- coding: utf-8 -*-
"""Structured Discussion-Question answers (kept as data, rendered as compact
tables in the report rather than long Q/A prose blocks)."""

QA_15 = {
    "diabetes": [
        ("Một observation đại diện cho điều gì?",
         "Một bệnh nhân, với các đặc trưng nhân khẩu học/lâm sàng và một nhãn tiểu đường."),
        ("Biểu diễn dữ liệu thô là gì?",
         "CSV 100.000 dòng × 9 cột: 6 biến số, 2 biến phân loại (gender, smoking_history), 1 mục tiêu."),
        ("Biểu diễn số cuối cùng là gì?",
         "Ma trận float64 (N, 15) sau StandardScaler (6 cột số) + OneHotEncoder (2 cột phân loại)."),
        ("Các chiều của ma trận đặc trưng có ý nghĩa gì?",
         "N=96.137 bệnh nhân sau làm sạch; d=15 đặc trưng sau mã hóa (8 gốc, gender/smoking mở rộng thành 9 cột nhị phân)."),
        ("Đặc trưng nào cần mã hóa?", "gender (3 nhóm), smoking_history (6 nhóm) — One-Hot Encoding."),
        ("Đặc trưng nào cần chuẩn hóa?",
         "age, bmi, HbA1c_level, blood_glucose_level, hypertension, heart_disease — StandardScaler."),
        ("Thông tin nào bị mất khi biểu diễn?",
         "Nhãn gốc của biến phân loại (thay bằng cột nhị phân); giá trị tuyệt đối của biến số (thay bằng giá trị đã chuẩn hóa)."),
        ("Thông tin nào được giữ lại?", "Toàn bộ thông tin lâm sàng, dưới dạng số đã chuẩn hóa/mã hóa."),
        ("Bước nào có thể gây rò rỉ dữ liệu?",
         "Fit Scaler/Encoder trên toàn bộ dữ liệu trước khi chia tập, hoặc fit lại khi triển khai — cả hai đều tránh được."),
        ("Mô hình nào tốt nhất?", "Decision Tree (ROC-AUC=0,9745 trên Validation, sát Random Forest 0,9744)."),
        ("Vì sao chọn mô hình đó?", "ROC-AUC cao nhất, huấn luyện nhanh hơn Random Forest (0,21s so với 4,19s) mà không giảm hiệu năng."),
        ("Độ đo nào quan trọng nhất?", "F1-score và ROC-AUC — do mất cân bằng lớp nặng (91%/9%)."),
        ("Mô hình lưu trữ ra sao?", "Đóng gói cùng ColumnTransformer trong 1 sklearn.Pipeline, lưu joblib + meta.json."),
        ("Web service dùng mô hình đã lưu ra sao?",
         "FastAPI tải pipeline khi khởi động, POST /predict gọi predict_proba(), trả nhãn + xác suất."),
        ("Mobile giao tiếp với dịch vụ dự đoán ra sao?",
         "Gửi HTTP POST tới cùng REST API (cổng 8000), không chạy mô hình trên thiết bị."),
    ],
    "house_price": [
        ("Một observation đại diện cho điều gì?", "Một tin đăng bán nhà/căn hộ, với đặc điểm vật lý/pháp lý và giá bán."),
        ("Biểu diễn dữ liệu thô là gì?", "CSV 30.229 dòng × 12 cột (1 cột địa chỉ tự do, 6 cột số, 4 cột phân loại, 1 cột giá)."),
        ("Biểu diễn số cuối cùng là gì?", "Ma trận float64 (N, 43) sau chuẩn hóa 6 cột số + One-Hot 5 cột phân loại (gồm ProvinceGroup trích từ Address)."),
        ("Các chiều của ma trận đặc trưng có ý nghĩa gì?", "N=30.229 tin đăng; d=43 tăng mạnh từ 11 gốc do các cột phân loại nhiều giá trị."),
        ("Đặc trưng nào cần mã hóa?", "Legal status, Furniture state, House/Balcony direction, ProvinceGroup — One-Hot Encoding."),
        ("Đặc trưng nào cần chuẩn hóa?", "Area, Frontage, Access Road, Floors, Bedrooms, Bathrooms — StandardScaler."),
        ("Thông tin nào bị mất khi biểu diễn?", "Chuỗi địa chỉ đầy đủ (chỉ giữ tỉnh/thành trích xuất); tên gốc các nhóm phân loại."),
        ("Thông tin nào được giữ lại?", "Đặc điểm cấu trúc, pháp lý/nội thất, và vị trí ở mức tỉnh/thành."),
        ("Bước nào có thể gây rò rỉ dữ liệu?", "Fit Scaler/Encoder trên toàn bộ 30.229 dòng trước khi chia tập, hoặc fit lại khi triển khai."),
        ("Mô hình nào tốt nhất?", "Gradient Boosting Regressor (RMSE=1,6238 tỷ, R²=0,4685 trên Validation)."),
        ("Vì sao chọn mô hình đó?", "RMSE thấp nhất, R² cao nhất — vượt các mô hình tuyến tính (R²≈0,32), cho thấy quan hệ phi tuyến."),
        ("Độ đo nào quan trọng nhất?", "RMSE — cùng đơn vị (tỷ VNĐ) với target, phạt nặng sai số lớn; R² bổ sung góc nhìn phương sai."),
        ("Mô hình lưu trữ ra sao?", "Đóng gói cùng ColumnTransformer trong 1 Pipeline, lưu joblib + meta.json (kèm danh sách tỉnh/thành hợp lệ)."),
        ("Web service dùng mô hình đã lưu ra sao?", "FastAPI tải pipeline, POST /predict gọi predict(), trả giá dự đoán (tỷ VNĐ)."),
        ("Mobile giao tiếp với dịch vụ dự đoán ra sao?", "Gửi HTTP POST tới REST API (cổng 8001), hiển thị giá trả về, không chạy mô hình trên thiết bị."),
    ],
    "ecommerce": [
        ("Một observation đại diện cho điều gì?", "Một đánh giá của khách hàng về một sản phẩm thời trang."),
        ("Biểu diễn dữ liệu thô là gì?", "CSV 23.486 dòng × 10 cột: số + phân loại + 2 cột văn bản tự do (Title, Review Text)."),
        ("Biểu diễn số cuối cùng là gì?", "Bảng: ma trận float64 (N, 35). Văn bản: ma trận thưa TF-IDF (16.415, 5.000)."),
        ("Các chiều của ma trận đặc trưng có ý nghĩa gì?", "N=23.451 đánh giá; d=35 (bảng) hoặc tối đa 5.000 từ/cụm từ (TF-IDF)."),
        ("Đặc trưng nào cần mã hóa?", "Division/Department/Class Name — One-Hot; Review Text — TF-IDF (khác One-Hot)."),
        ("Đặc trưng nào cần chuẩn hóa?", "Age, Rating, Positive Feedback Count, Review/Title Length, Has Review, Has Title — StandardScaler."),
        ("Thông tin nào bị mất khi biểu diễn?", "Nội dung câu chữ cụ thể (bảng); cấu trúc câu, ngữ nghĩa sâu, từ ngoài từ điển 5.000 từ (TF-IDF)."),
        ("Thông tin nào được giữ lại?", "Rating, nhóm sản phẩm, hành vi viết đánh giá (bảng); trọng số từ/cụm từ quan trọng (TF-IDF)."),
        ("Bước nào có thể gây rò rỉ dữ liệu?", "Fit TfidfVectorizer/Scaler/Encoder trên dữ liệu ngoài tập Train, hoặc fit lại khi triển khai."),
        ("Mô hình nào tốt nhất?", "SVM trên biểu diễn dạng bảng (F1=0,9528 Validation, F1=0,9614 Test)."),
        ("Vì sao chọn mô hình đó?", "F1 cao nhất nhóm mô hình bảng; mô hình văn bản tốt hơn baseline nhưng thấp hơn (F1=0,9288) và cần dữ liệu chỉ có sau khi khách viết đánh giá."),
        ("Độ đo nào quan trọng nhất?", "F1-score — do mất cân bằng lớp (82%/18%), Accuracy dễ gây hiểu lầm."),
        ("Mô hình lưu trữ ra sao?", "Hai pipeline joblib riêng: model_pipeline (bảng+SVM) và text_model_pipeline (TF-IDF+Logistic Regression)."),
        ("Web service dùng mô hình đã lưu ra sao?", "FastAPI có 2 endpoint: POST /predict (bảng) và POST /analyze_text (văn bản)."),
        ("Mobile giao tiếp với dịch vụ dự đoán ra sao?", "Gửi HTTP POST tới REST API (cổng 8002) cho cả 2 endpoint, hiển thị nhãn + xác suất."),
    ],
}

QA_ECOMMERCE_EXTRA = [
    ("Nội dung bình luận khách hàng chứa thông tin gì?",
     "Mức độ hài lòng, nhận xét chất lượng/kích cỡ/chất liệu, trải nghiệm sử dụng."),
    ("Bình luận được chuyển thành dữ liệu số như thế nào?",
     "TfidfVectorizer: từ điển tối đa 5.000 token (unigram+bigram) học từ tập Train, mỗi đánh giá → 1 vector trọng số TF-IDF."),
    ("Token ID đại diện cho điều gì?",
     "Chỉ số cột trong ma trận thưa TF-IDF (tương đương Token ID trong sơ đồ Token→ID→Embedding), không phải embedding ngữ nghĩa đầy đủ."),
    ("Vector embedding đại diện cho điều gì?",
     "Hệ thống dùng trọng số TF-IDF thay vì embedding học sâu — vẫn là biểu diễn số về mức độ quan trọng từng từ, nhưng chưa nắm bắt ngữ nghĩa sâu."),
    ("Những sở thích khách hàng nào có thể phát hiện?",
     "Liên hệ Rating ↔ khả năng đề xuất; khác biệt tỉ lệ đề xuất theo ngành hàng; khác biệt hành vi viết đánh giá."),
    ("Văn bản có cải thiện dự đoán so với chỉ dùng bảng không?",
     "Không — mô hình chỉ dùng văn bản (F1=0,9288) thấp hơn mô hình bảng tốt nhất (F1=0,9528); Rating/đặc trưng sản phẩm vẫn là tín hiệu mạnh hơn."),
]
